ViniciusGR797/crm_union

README.md
Antes de fazer os trabalhos, é bom resolver este pequeno problema em que as branches estão acusando README.md como diferentes já que elas tiveram commits iguais separadamente. Por isso, a branch develop diz "This branch is [2 commits ahead], [3 commits behind] main", o que não é verdade
=> Sincronizar develop e main

microservice_group/cmd/main.go, microservice_group/config/config.go
Arrumando bug da porta que estava acontecendo :X
=> arrumando bug da port

microservice_group/pkg/controller/controller.go, microservice_group/pkg/entity/Entity.go, microservice_group/pkg/routes/routes.go, microservice_group/pkg/service/service.go
=> softDelete_Groups

microservice_release/pkg/controller/controller.go, microservice_release/pkg/database/database.go, microservice_release/pkg/routes/routes.go, microservice_release/pkg/service/service.go
=> Get release by 

microservice_client/pkg/controller/controller.go, microservice_client/pkg/routes/routes.go, microservice_client/pkg/service/service.go
Método para buscar cliente através do ID
=> getClientByID

microservice_client/pkg/controller/controller.go, microservice_client/pkg/entity/entity.go, microservice_client/pkg/routes/routes.go, microservice_client/pkg/service/service.go
Criado método de inserção de tags nos clientes e criação de clientes com a opção de enviar tags atribuídas;
=> createClient e InsertTagClient

microservice_group/pkg/entity/Entity.go, microservice_group/pkg/service/service.go, microservice_subject/cmd/main.go, microservice_subject/config/config.go, microservice_subject/pkg/controller/controller.go, microservice_subject/pkg/database/database.go, microservice_subject/pkg/database/mysql.go, microservice_subject/pkg/entity/entity.go, microservice_subject/pkg/routes/routes.go, microservice_subject/pkg/server/server.go, microservice_subject/pkg/service/service.go
Atualizamos a função de criar group, começamos a Subject com a rota get all e getId
=> fução getall subjects e byID

microservice_customer/pkg/controller/controller.go, microservice_customer/pkg/entity/entity.go, microservice_customer/pkg/routes/routes.go, microservice_customer/pkg/service/service.go
Atualizado o customer update e criado o softDelete alem de ter padronizado todas as rotas
=> Update atualizado e softDelete

microservice_group/pkg/controller/controller.go, microservice_group/pkg/entity/Entity.go, microservice_group/pkg/routes/routes.go, microservice_group/pkg/service/service.go, microservice_subject/pkg/controller/controller.go, microservice_subject/pkg/entity/entity.go, microservice_subject/pkg/routes/routes.go, microservice_subject/pkg/service/service.go
=> adicionando varias novas rotas

microservice_client/pkg/controller/controller.go, microservice_client/pkg/entity/entity.go, microservice_client/pkg/routes/routes.go, microservice_client/pkg/service/service.go
=> criado update_client_tag

microservice_client/pkg/controller/controller.go, microservice_client/pkg/entity/entity.go, microservice_client/pkg/service/service.go
Concluído as tratativas de erros e inclusão dos status corretos
=> Concluído as tratativas de erros e inclusão dos status corretos

microservice_release/pkg/service/service.go
=> tratamento de erro

main.go, microservice_group/pkg/controller/controller.go, microservice_group/pkg/entity/Entity.go, microservice_group/pkg/service/service.go, microservice_subject/pkg/controller/controller.go, microservice_subject/pkg/entity/entity.go, microservice_subject/pkg/routes/routes.go, microservice_subject/pkg/service/service.go
finalização das rotas mais as tratavivas de erro (❁´◡`❁)
=> finalização das rotas mais as tratavivas de erro

microservice_group/pkg/controller/controller.go, microservice_group/pkg/service/service.go, microservice_subject/pkg/controller/controller.go, microservice_subject/pkg/service/service.go
=> Herher goup coment

microservice_customer/pkg/controller/controller.go, microservice_customer/pkg/database/database.go, microservice_customer/pkg/database/mysql.go, microservice_customer/pkg/entity/entity.go, microservice_customer/pkg/middlewares/auth.go, microservice_customer/pkg/routes/routes.go, microservice_customer/pkg/security/token.go, microservice_customer/pkg/server/server.go, microservice_customer/pkg/service/service.go, microservice_remark/cmd/main.go, microservice_remark/config/config.go, microservice_remark/pkg/controller/controller.go, microservice_remark/pkg/database/database.go, microservice_remark/pkg/database/mysql.go, microservice_remark/pkg/entity/entity.go, microservice_remark/pkg/routes/routes.go, microservice_remark/pkg/server/server.go, microservice_remark/pkg/service/service.go
Criado Comentário  Remark e Customer
=> Comentario da api

microservice_business/pkg/controller/controller.go, microservice_business/pkg/middlewares/auth.go, microservice_business/pkg/routes/routes.go, microservice_business/pkg/security/token.go, microservice_client/pkg/middlewares/auth.go, microservice_client/pkg/security/token.go, microservice_customer/pkg/controller/controller.go, microservice_customer/pkg/middlewares/auth.go, microservice_customer/pkg/routes/routes.go, microservice_customer/pkg/security/token.go, microservice_group/pkg/controller/controller.go, microservice_group/pkg/middlewares/auth.go, microservice_group/pkg/routes/routes.go, microservice_group/pkg/security/token.go, microservice_planner/pkg/middlewares/auth.go, microservice_planner/pkg/security/token.go, microservice_release/pkg/controller/controller.go, microservice_release/pkg/middlewares/auth.go, microservice_release/pkg/routes/routes.go, microservice_release/pkg/security/token.go, microservice_remark/pkg/middlewares/auth.go, microservice_remark/pkg/security/token.go, microservice_subject/pkg/middlewares/auth.go, microservice_subject/pkg/security/token.go, microservice_user/pkg/controller/controller.go, microservice_user/pkg/middlewares/auth.go, microservice_user/pkg/routes/routes.go, microservice_user/pkg/security/token.go
para separar a validação de administrador dos controllers das rotas
=> Middleware de autenticação de administrador

.gitignore, go.work.sum, microservice_customer/pkg/routes/routes.go, microservice_remark/pkg/routes/routes.go, microservice_subject/pkg/service/service.go
ajustando imports customer, remark e subject
=> ajustando imports customer, remark e subject

.gitignore, README.md, microservice_business/pkg/controller/controller.go, microservice_business/pkg/service/service.go, microservice_client/pkg/controller/controller.go, microservice_client/pkg/routes/routes.go, microservice_client/pkg/service/service.go, microservice_customer/pkg/controller/controller.go, microservice_customer/pkg/service/service.go, microservice_group/pkg/controller/controller.go, microservice_group/pkg/service/service.go
add variáveis de sessão, utilização de logs e arquivos docker
=> add variáveis de sessão, utilização de logs e arquivos docker

microservice_planner/pkg/entity/entity.go, microservice_planner/pkg/service/service.go
added remark on planner service functions
=> Planner add remark

microservice_subject/pkg/entity/entity.go, microservice_subject/pkg/service/service.go
Incrementamos os IDs, conforme foi pedido pelo o Leonardo, no microservice Subject.
=> Atualização no código

microservice_group/pkg/controller/controller.go, microservice_group/pkg/database/mysql.go, microservice_group/pkg/service/service.go
=> Testando o ctx

microservice_group/pkg/entity/Entity.go, microservice_group/pkg/service/service.go
Por favor testar as rotas, pois não estou conseguindo roda a aplicação em minha maquina.
=> Adicionado o Responsible em group
